# Site
title: Ricky (liqimore)的个人博客
subtitle: things to remember
description: liqimore的个人生活博客,学习计算机科学与技术(CS),这个博客用来记录生活,与技术博客分割开来.
keywords: ricky li, 李祺, liqimore, liqitry
author: Ricky Li

menu:
  归档: /archives
  旅行: /categories/travel
  随想: /categories/thoughts
  生活: /categories/life
  关于: /about

